[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
gas_reports = ['*']
solc_version = "0.8.30"
build_info = true
extra_output = ["storageLayout"]
dynamic_test_linking = true
fs_permissions = [{ access = "read-write", path = "." }]
evm_version = "cancun"

[profile.deploy]
optimizer_runs = 10_000

[profile.solx]
gas_limit = 100_000_000

[lint]
exclude_lints = ["mixed-case-function","screaming-snake-case-immutable","pascal-case-struct", "mixed-case-variable", "unsafe-cheatcode"]

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
sort_imports = true

[dependencies]
solady = "0.1.26"
minimal-smart-account = { version = "1.0", git = "https://github.com/turingcapitalgroup/minimal-smart-account.git"}
forge-std = "1.11.0"
kam = { version = "1.0", git = "https://github.com/turingcapitalgroup/kam.git" }

[soldeer]
# whether soldeer manages remappings
remappings_generated = false
# whether soldeer re-generates all remappings when installing, updating or uninstalling deps
remappings_regenerate = false
# whether to suffix the remapping with the version: `name-a.b.c`
remappings_version = false
