[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
gas_reports = ['*']
solc_version = "0.8.30"
build_info = true
extra_output = ["storageLayout"]
dynamic_test_linking = true
fs_permissions = [{ access = "read-write", path = "." }]
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
via_ir = true

[profile.deploy]
optimizer = true
optimizer_runs = 200
via_ir = true

[profile.solx]
gas_limit = 100_000_000

[lint]
exclude_lints = ["mixed-case-function","screaming-snake-case-immutable","pascal-case-struct", "mixed-case-variable", "unsafe-cheatcode"]
exclude_paths = ["src/vendor"]

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
sort_imports = true

[doc]
out = "foundry-docs/"
title = "MetaWallet Contracts Documentation"

[dependencies]
minimal-smart-account = { version = "1.0", git = "https://github.com/turingcapitalgroup/minimal-smart-account.git"}
forge-std = "1.11.0"
kam = { version = "1.0", git = "https://github.com/turingcapitalgroup/kam.git" }
minimal-uups-factory = { version = "1.0.0", git = "https://github.com/turingcapitalgroup/minimal-uups-factory.git", rev = "f484679b34fc4ffe4f394bb3b9417e81d462fa8c" }

[soldeer]
# whether soldeer manages remappings
remappings_generated = false
# whether soldeer re-generates all remappings when installing, updating or uninstalling deps
remappings_regenerate = false
# whether to suffix the remapping with the version: `name-a.b.c`
remappings_version = false
