[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
gas_reports = ['*']
solc_version = "0.8.30"
zast = true
build_info = true
extra_output = ["storageLayout"]
dynamic_test_linking = true
fs_permissions = [{ access = "read-write", path = "." }]

[profile.deploy]
optimizer_runs = 10_000

[profile.solx]
optimization = 3
gas_limit = 100_000_000

[lint]
exclude_lints = ["mixed-case-function","screaming-snake-case-immutable","pascal-case-struct", "mixed-case-variable"]

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true
sort_imports = true

[dependencies]
solady = "0.1.26"
kam = { version = "1.0", git = "https://github.com/turingcapitalgroup/kam.git", rev = "bc3b567962df48f8c70ec2c2eafc696b872453fc" }
minimal-smart-account = { version = "1.0", git = "https://github.com/turingcapitalgroup/minimal-smart-account.git", rev = "d2c304a9f64f445a4566f81efd792ac25a129371" }
forge-std = "1.11.0"

[soldeer]
# whether soldeer manages remappings
remappings_generated = false
# whether soldeer re-generates all remappings when installing, updating or uninstalling deps
remappings_regenerate = false
# whether to suffix the remapping with the version: `name-a.b.c`
remappings_version = false
